---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-sprint-rps-calc
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-sprint-rps-calc
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-sprint-rps-calc
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/pttg-cfssl-sidekick:build-6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=pttg-rps.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.6
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '9000'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ADD_NGINX_SERVER_CFG
            value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.1.1
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - --config=/etc/secrets/keycloak-api-secret.yaml
          - --discovery-url=https://sso.digital.homeoffice.gov.uk/auth/realms/{{.KC_REALM}}
          - --client-id=pttg-rps-{{.ENVIRONMENT}}
          - --listen=127.0.0.1:9000
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8000
          - --no-redirects=false
          - --redirection-url=https://fs.calc.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
          - --cors-origins='*'
          - --resources=uri=/healthz|white-listed=true
          - --resources=uri=/|methods=GET,POST|roles=pttg-rps
          - --secure-cookie=true
          - --http-only-cookie=true
          - --verbose
        ports:
          - name: keycloak-http
            containerPort: 9000
        volumeMounts:
        - name: keycloak-api-secret
          mountPath: /etc/secrets
          readOnly: true
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
      - name: pttg-sprint-rps-calc
        image: quay.io/ukhomeofficedigital/pttg-sprint-rps-calc:{{.VERSION}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: PORT
            value: "8000"
          - name: CA_CERTS_PATH
            value: "/certs/tls.pem"
          - name: IP_API_AUTH
            valueFrom:
              secretKeyRef:
                name: pttg-ip-api-service-secrets
                key: pttg_ip_fm_ui
          - name: PROXY_DISCOVERY_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: PROXY_DISCOVERY_URL
          - name: PROXY_REDIRECTION_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: PROXY_REDIRECTION_URL
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pttg-dev-smtp
                key: smtp_password
          - name: SMTP_SERVER
            valueFrom:
              secretKeyRef:
                name: pttg-dev-smtp
                key: smtp_server
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: pttg-dev-smtp
                key: smtp_username
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
      volumes:
      - name: certs
        emptyDir:
          medium: "Memory"
      - name: keycloak-api-secret
        secret:
          secretName: keycloak-api-secret
