---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/whitelist-source-range: "{{.WHITELIST}}"
    stable.k8s.psg.io/kcm.provider: http
  name: pttg-rps-calc-ingress-external
spec:
  tls:
  - hosts:
    - calc-rps.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    secretName: letsencrypt-pttg-fs-ui-calc
  rules:
  - host: calc-rps.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: pttg-sprint-rps-calc
          servicePort: 443