---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/whitelist-source-range: "{{.WHITELIST}}"
  name: pttg-sprint-rps-calc
spec:
  rules:
  - host: calc.rps.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: pttg-sprint-rps-calc
          servicePort: 443
        path: /
  tls:
  - hosts:
    - calc.rps.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    secretName: letsencrypt-tls-pttg-sprint-rpc-calc
